model_params:
  model: BinaryDensenet
  pretrain: densenet121

# distributed_params:
#   opt_level: O1
#   syncbn: True

stages:
  state_params:
    main_metric: wauc
    minimize_metric: False

  data_params:
    num_workers: 16
    batch_size: 16
    folds: data/combined.csv
    fold_index: 0

  criterion_params:
    criterion: BCEWithLogitsLoss

  callbacks_params:
    loss:
      callback: CriterionCallback

    optim:
      callback: OptimizerCallback
      # accumulation_steps: 16

    spearman:
      callback: WeightedAUC

    saver:
      callback: CheckpointCallback

    # early_stopping:
    #   callback: EarlyStoppingCallback
    #   patience: 3
    #   metric: spearman
    #   minimize: False

  stage1:
    state_params:
      num_epochs: 10
    
    optimizer_params:
      optimizer: Adam
      lr: 0.003

  stage2:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: Adam
      lr: 0.0001
  
  stage3:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: Adam
      lr: 0.00001
