model_params:
  model: BinaryEfficientNet
  pretrain: efficientnet-b0

# distributed_params:
#   opt_level: O1
#   syncbn: True

stages:
  state_params:
    main_metric: wauc
    minimize_metric: False

  data_params:
    num_workers: 16
    batch_size: 16
    folds: data/combined.csv
    fold_index: 0

  criterion_params:
    criterion: BCEWithLogitsLoss

  # scheduler_params:
  #   scheduler: CosineAnnealingWithRestartsLR

  stage1_sampler:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: Adam
      lr: 0.0005

    callbacks_params:
      loss:
        callback: CriterionCallback

      optim:
        callback: OptimizerCallback

      wauc:
        callback: WeightedAUC

      saver:
        callback: CheckpointCallback
        load_on_stage_start:
          model: ./logs/efficientnet-b0-magic-constant/checkpoints/best.pth

  stage2:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: Adam
      lr: 0.00025

    callbacks_params:
      loss:
        callback: CriterionCallback

      optim:
        callback: OptimizerCallback

      wauc:
        callback: WeightedAUC

      saver:
        callback: CheckpointCallback

  stage3:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: Adam
      lr: 0.00005

    callbacks_params:
      loss:
        callback: CriterionCallback

      optim:
        callback: OptimizerCallback

      wauc:
        callback: WeightedAUC

      saver:
        callback: CheckpointCallback
