model_params:
  model: BinaryEfficientNet
  pretrain: efficientnet-b0

# distributed_params:
#   opt_level: O1
#   syncbn: True

stages:
  state_params:
    main_metric: wauc
    minimize_metric: False

  data_params:
    num_workers: 16
    loaders_params:
      train:
        batch_size: 12
      valid:
        batch_size: 32
    folds: data/combined.csv
    fold_index: 0
    train_dataset:
      mixup_alpha: [0.1, 0.4]
      mixup_prob: 0.25


  criterion_params:
    criterion: BCEWithLogitsLoss

  # scheduler_params:
  #   scheduler: CosineAnnealingWithRestartsLR

  stage1:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: Adam
      lr: 0.00001

    callbacks_params:
      loss:
        callback: CriterionCallback

      optim:
        callback: OptimizerCallback

      wauc:
        callback: WeightedAUC
        mixup_threshold: 0.5

      saver:
        callback: CheckpointCallback
        load_on_stage_start:
          model: ./logs/efficientnet-b0-magic-constant-continue2/checkpoints/best.pth
        save_n_best: 2

  stage2:
    state_params:
      num_epochs: 5
    
    optimizer_params:
      optimizer: Adam
      lr: 0.000005

    callbacks_params:
      loss:
        callback: CriterionCallback

      optim:
        callback: OptimizerCallback

      wauc:
        callback: WeightedAUC
        mixup_threshold: 0.5

      saver:
        callback: CheckpointCallback
        save_n_best: 2

