
# Classes:
#   0 - cover images (without modification)
#   1 - jmipod
#   2 - juniward
#   3 - uerd

model_params:
  model: MulticlassEfficientNet
  pretrain: efficientnet-b0
  n_classes: 4

# distributed_params:
#   opt_level: O1
#   syncbn: True

stages:
  state_params:
    main_metric: wauc
    minimize_metric: False

  data_params:
    num_workers: 16
    loaders_params:
      train:
        batch_size: 32
      valid:
        batch_size: 64
    folds: data/combined.csv
    fold_index: 0
    is_multiclass: True

  criterion_params:
    criterion: LabelSmoothingLoss
    smoothing: 0.1

  # scheduler_params:
  #   scheduler: CosineAnnealingWithRestartsLR

  callbacks_params:
    loss:
      callback: CriterionCallback

    optim:
      callback: OptimizerCallback
      # accumulation_steps: 16

    wauc:
      callback: SingleClassWeightedAUC
      class_index: 0
      metric_name: wauc

    saver:
      callback: CheckpointCallback

    # scheduler:
    #   callback: SchedulerCallback

    # early_stopping:
    #   callback: EarlyStoppingCallback
    #   patience: 3
    #   metric: spearman
    #   minimize: False

  stage1:
    state_params:
      num_epochs: 10
    
    optimizer_params:
      optimizer: AdamW
      lr: 0.0003
