model_params:
  model: BinaryEfficientNet
  pretrain: efficientnet-b0

# distributed_params:
#   opt_level: O1
#   syncbn: True

stages:
  state_params:
    main_metric: wauc
    minimize_metric: False

  data_params:
    num_workers: 16
    loaders_params:
      train:
        batch_size: 32
      valid:
        batch_size: 64
    folds: data/combined.csv
    fold_index: 0

  criterion_params:
    criterion: BCEWithLogitsLoss

  # scheduler_params:
  #   scheduler: CosineAnnealingWithRestartsLR

  callbacks_params:
    loss:
      callback: CriterionCallback

    optim:
      callback: OptimizerCallback
      # accumulation_steps: 16

    wauc:
      callback: WeightedAUC

    saver:
      callback: CheckpointCallback

    # scheduler:
    #   callback: SchedulerCallback

    # early_stopping:
    #   callback: EarlyStoppingCallback
    #   patience: 3
    #   metric: spearman
    #   minimize: False

  stage1:
    state_params:
      num_epochs: 20
    
    optimizer_params:
      optimizer: Adam
      lr: 0.0003
